### ISSUE TITLE
A Job's Initcontainer cannot call a localhost CONFIGURATION_SERVICE

### ISSUE THREAD

**Issue by donovanmuller** [didiladi/keptn-generic-job-service#4]
Given this job service running in a execution plane (separate cluster from control plane) and a `Deployment` configuration such as:

```yaml
...
     spec:                                                                                                                                                      
       containers:                                                                                                                                              
       - env:                                                                                                                                                   
         - name: CONFIGURATION_SERVICE                                                                                                                          
           value: http://localhost:8081/configuration-service                                                                                                   
         - name: KEPTN_CONFIGURATION_SERVICE_API_ENDPOINT                                                                                                       
           value: http://localhost:8081/configuration-service                                                                                                   
         - name: JOB_NAMESPACE                                                                                                                                  
           value: keptn                                                                                                                                         
         image: didiladi/keptn-generic-job-service:latest
...
```

and a new `Job` created based on an event trigger. 

The new `Job` will have the value of `CONFIGURATION_SERVICE` (`http://localhost:8081/configuration-service`) above used as the Job's initContainer `CONFIGURATION_SERVICE` environment variable as well:

```yaml
...
   initContainers:                                                                                                                                              
   - env:                                                                                                                                                       
     - name: ENV                                                                                                                                                
     - name: CONFIGURATION_SERVICE                                                                                                                              
       value: http://localhost:8081/configuration-service                                                                                                       
     - name: KEPTN_API_TOKEN                                                                                                                                    
     - name: KEPTN_PROJECT                                                                                                                                      
       value: engine-debug-1                                                                                                                                    
     - name: KEPTN_STAGE                                                                                                                                        
       value: staging                                                                                                                                           
     - name: KEPTN_SERVICE                                                                                                                                      
       value: engine                                                                                                                                            
     - name: JOB_ACTION                                                                                                                                         
       value: Test dupes                                                                                                                                        
     - name: JOB_TASK                                                                                                                                           
       value: Test wait
...
```

This means that the Job fails as there is no `distributor` running and accessible at `localhost:8081`:

```
init-keptn-generic-job-22b184c0-7266-4fad-b047-72006514aca2-1 2021/05/08 06:50:52 Could not find config for generic Job service                                
init-keptn-generic-job-22b184c0-7266-4fad-b047-72006514aca2-1 2021/05/08 06:50:52 Error while copying files: resource not found: generic-job/config.yaml - Get 
https://localhost:8081/configuration-service/v1/project/engine-debug-1/stage/staging/service/engine/resource/generic-job%2Fconfig.yaml: dial tcp 127.0.0.1:80 
81: connect: connection refused
```

The one to one relationship between this job service's `CONFIGURATION_SERVICE` and the spawned Job's doesn't seem to allow for a working runnable `Job`?
